package com.oxy.s3m.notification.model.seller;
// Generated Sep 5, 2017 4:03:09 PM by Hibernate Tools 5.2.3.Final

import java.sql.*;
import java.util.HashSet;
import java.util.Set;

/**
 * SellerDetails generated by hbm2java
 */
public class SellerDetails implements java.io.Serializable {

	private Integer sellerId;
	private String sellerName;
	private String deviceId;
	private String fcmToken;
	private Timestamp dateCreated;
	private Boolean active;
	private String status;
	private Set<SellerCategories> sellerCategorieses = new HashSet<SellerCategories>(0);
	private Set<SellerAddress> sellerAddresses = new HashSet<SellerAddress>(0);
	private Set<SellerInterests> sellerInterests = new HashSet<SellerInterests>(0);
	private String Agreement;
	
	public Set<SellerInterests> getSellerInterests() {
		return sellerInterests;
	}

	public void setSellerInterests(Set<SellerInterests> sellerInterests) {
		this.sellerInterests = sellerInterests;
	}

	
	
	
	
	
	public String getAgreement() {
		return Agreement;
	}

	public void setAgreement(String agreement) {
		Agreement = agreement;
	}

	public SellerDetails() {
	}

	public SellerDetails(String sellerName, Timestamp dateCreated) {
		this.sellerName = sellerName;
		this.dateCreated = dateCreated;
	}

	public SellerDetails(String sellerName, String deviceId, String fcmToken, Timestamp dateCreated, Boolean active,
			String status, Set<SellerCategories> sellerCategorieses, Set<SellerAddress> sellerAddresses) {
		this.sellerName = sellerName;
		this.deviceId = deviceId;
		this.fcmToken = fcmToken;
		this.dateCreated = dateCreated;
		this.active = active;
		this.status = status;
		this.sellerCategorieses = sellerCategorieses;
		this.sellerAddresses = sellerAddresses;
	}

	public Integer getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Integer sellerId) {
		this.sellerId = sellerId;
	}

	public String getSellerName() {
		return this.sellerName;
	}

	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getFcmToken() {
		return this.fcmToken;
	}

	public void setFcmToken(String fcmToken) {
		this.fcmToken = fcmToken;
	}

	public Timestamp getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Timestamp dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<SellerCategories> getSellerCategorieses() {
		return this.sellerCategorieses;
	}

	public void setSellerCategorieses(Set<SellerCategories> sellerCategorieses) {
		this.sellerCategorieses = sellerCategorieses;
	}

	public Set<SellerAddress> getSellerAddresses() {
		return this.sellerAddresses;
	}

	public void setSellerAddresses(Set<SellerAddress> sellerAddresses) {
		this.sellerAddresses = sellerAddresses;
	}

}
