package com.oxy.s3m.notification.model.seller;
// Generated Sep 18, 2017 11:09:55 PM by Hibernate Tools 5.2.3.Final

import com.oxy.s3m.notification.model.customer.MasterArea;

/**
 * SellerInterests generated by hbm2java
 */
public class SellerInterests implements java.io.Serializable {

	private Integer id;
	private MasterArea masterArea;
	private int sellerId;

	public SellerInterests() {
	}

	public SellerInterests(MasterArea masterArea, int sellerId) {
		this.masterArea = masterArea;
		this.sellerId = sellerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MasterArea getMasterArea() {
		return this.masterArea;
	}

	public void setMasterArea(MasterArea masterArea) {
		this.masterArea = masterArea;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

}
