package com.oxy.s3m.notification.model.seller;
// Generated Sep 5, 2017 4:03:09 PM by Hibernate Tools 5.2.3.Final

import com.oxy.s3m.notification.model.categories.Categories;

/**
 * SellerCategories generated by hbm2java
 */
public class SellerCategories implements java.io.Serializable {

	private Integer id;
	private Categories categories;
	private SellerDetails sellerDetails;

	public SellerCategories() {
	}

	public SellerCategories(Categories categories, SellerDetails sellerDetails) {
		this.categories = categories;
		this.sellerDetails = sellerDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public SellerDetails getSellerDetails() {
		return this.sellerDetails;
	}

	public void setSellerDetails(SellerDetails sellerDetails) {
		this.sellerDetails = sellerDetails;
	}

}
