package com.oxy.s3m.notification.model.seller;
// Generated Sep 5, 2017 4:03:09 PM by Hibernate Tools 5.2.3.Final

/**
 * SellerAddress generated by hbm2java
 */
public class SellerAddress implements java.io.Serializable {

	private Integer id;
	private SellerDetails sellerDetails;
	private String sellerPh;
	private String sellerCountry;
	private String sellerState;
	private String sellerCity;
	private String sellerArea;
	private String address;

	public SellerAddress() {
	}

	public SellerAddress(String sellerPh, String sellerCountry, String sellerState) {
		this.sellerPh = sellerPh;
		this.sellerCountry = sellerCountry;
		this.sellerState = sellerState;
	}

	public SellerAddress(SellerDetails sellerDetails, String sellerPh, String sellerCountry, String sellerState,
			String sellerCity, String sellerArea, String address) {
		this.sellerDetails = sellerDetails;
		this.sellerPh = sellerPh;
		this.sellerCountry = sellerCountry;
		this.sellerState = sellerState;
		this.sellerCity = sellerCity;
		this.sellerArea = sellerArea;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SellerDetails getSellerDetails() {
		return this.sellerDetails;
	}

	public void setSellerDetails(SellerDetails sellerDetails) {
		this.sellerDetails = sellerDetails;
	}

	public String getSellerPh() {
		return this.sellerPh;
	}

	public void setSellerPh(String sellerPh) {
		this.sellerPh = sellerPh;
	}

	public String getSellerCountry() {
		return this.sellerCountry;
	}

	public void setSellerCountry(String sellerCountry) {
		this.sellerCountry = sellerCountry;
	}

	public String getSellerState() {
		return this.sellerState;
	}

	public void setSellerState(String sellerState) {
		this.sellerState = sellerState;
	}

	public String getSellerCity() {
		return this.sellerCity;
	}

	public void setSellerCity(String sellerCity) {
		this.sellerCity = sellerCity;
	}

	public String getSellerArea() {
		return this.sellerArea;
	}

	public void setSellerArea(String sellerArea) {
		this.sellerArea = sellerArea;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
